### ISSUE TITLE
Editing a game in my collection doesn't work

### ISSUE THREAD

**Issue by amselem** [przepinski/bgguwp#8]
I enter a game card wich is in my collection, in the card the status "owned" is correctly checked.
Then I press the "Edit" button and I can see that the "owned" checkbox is not checked.
If I check "owned", then press "Save", the app crashes.

**Comment by rzepinskip** [comment]
I suppose it was connected with issue #7. Should be fixed in bd040e695c3befec761c1e5f9b90eac4347a7938.

**Comment by amselem** [comment]
I still have issues editing games. This is how I can repro:
I enter a game item (eg: 7 wonders duel), the game card shows "owned" as checked correctly. Then press "Edit" and the popup shows. However the "Owned" checkbox in the popup is cleared (I expected to be checked). 
Then I mark the "Owned" and "Want to Play" checkboxes then press "Cancel", then press "Edit" again and the two checkbox are still marked (I expected both to be clear, since I cancelled).
If I press "Save" instead, the popup closes and the "Edit" button backs to "+ Add" button (?)
If then I press "Back" my game collection is entirely cleared except for one generic game item (no title/picture), if I press this item the app crashes.

**Comment by rzepinskip** [comment]
Temporarily fixed in 55254a8689cd77d3c8ef8398cf71234e15e9e159. Will add proper support for duplicates in future.
